export type WorkflowNodeKind = 'collector' | 'dedupe' | 'judge' | 'writer' | 'formatter' | 'publisher' | 'notify' | 'split';

export type WorkflowNode = {
  id: string;
  name: string;
  kind: WorkflowNodeKind;
  description: string;
  usesAi: boolean;
  model?: string;
  reasoningEffort?: string;
  output: string;
  compactLabel: string;
};

export type WorkflowGroup = {
  id: string;
  title: string;
  badge: string;
  summary: string;
  sourceEntry: string;
  routingNote: string;
  defaultStatus: string;
  filterTags: string[];
  nodes: WorkflowNode[];
  routes?: {
    label: string;
    steps: string[];
  }[];
};

export const workflowFilters = [
  { key: 'all', label: '全部' },
  { key: 'x', label: 'X' },
  { key: 'crypto', label: 'Crypto' },
  { key: 'ai', label: 'AI' },
  { key: 'mixed', label: '混合' },
  { key: 'competitor', label: '竞品' },
  { key: 'jin10', label: '金十' },
  { key: 'alert', label: '标题提醒' },
] as const;

export type WorkflowFilterKey = (typeof workflowFilters)[number]['key'];

export const workflowGroups: WorkflowGroup[] = [
  {
    id: 'x_pipeline',
    title: 'X 主线',
    badge: 'write_flow',
    summary: 'X 账号内容先按账号配置进入 Crypto 或 AI 判断，再统一查重、写作、定稿和发布。',
    sourceEntry: "tasks.source = 'x'",
    routingNote: '普通 X 账号走判断者-Crypto；标记为 AI信源 的 X 账号仍保留 source=x，但进入判断者-AI，保留后按 X 常规快讯写作。',
    defaultStatus: "pending -> publisher_pending -> auto_published / publisher_pending",
    filterTags: ['x'],
    nodes: [
      {
        id: 'x_collect',
        name: '收集者-X',
        kind: 'collector',
        description: '按控制台账号规则抓取公开内容，保留原始作者字段，并缓存写作名与 AI信源标记。',
        usesAi: false,
        output: "写入 tasks.source='x'，提交本地 write_flow job。",
        compactLabel: 'X',
      },
      {
        id: 'x_route',
        name: '账号分流',
        kind: 'split',
        description: '依据 x_capture_accounts.is_ai_source 决定进入 Crypto 判断还是 AI 判断。',
        usesAi: false,
        output: '普通账号进入 judge_crypto；AI账号进入 judge_ai。',
        compactLabel: 'route',
      },
      {
        id: 'x_judge_crypto',
        name: '判断者-Crypto',
        kind: 'judge',
        description: '判断是否是可发布的 Crypto 快讯，并给出 regular / onchain / funding 等写作类型。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: '保留后进入搜索者；低价值内容写为 discarded。',
        compactLabel: 'judge_crypto',
      },
      {
        id: 'x_judge_ai',
        name: '判断者-AI',
        kind: 'judge',
        description: '只处理被标记为 AI信源 的 X 账号，判断是否有足够事实密度和产业价值。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: "保留后 news_type='regular'，继续使用 X 常规模板。",
        compactLabel: 'judge_ai',
      },
      {
        id: 'x_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '做 Odaily 历史查重和运行中 candidate 去重，必要时交给 AI 复核。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '重复内容结束为 duplicate；新内容进入写作。',
        compactLabel: 'search',
      },
      {
        id: 'x_write',
        name: '编写者1',
        kind: 'writer',
        description: '根据判断阶段的 news_type 选择 X 常规、链上或融资模板，生成标题和正文草稿。',
        usesAi: true,
        model: 'odaily-gpt-writer',
        reasoningEffort: 'low',
        output: '生成 draft_title / draft_content。',
        compactLabel: 'write',
      },
      {
        id: 'x_format',
        name: '编写者2',
        kind: 'formatter',
        description: '规范标题和正文格式，不负责最终发布决策。',
        usesAi: false,
        output: '产出 final_title / final_content，推进到 publisher_pending。',
        compactLabel: 'format',
      },
      {
        id: 'x_publish',
        name: '发布者',
        kind: 'publisher',
        description: '按发布者规则决定自动发布或挂后台，并在结束后发送统一通知。',
        usesAi: false,
        output: 'auto_published / publisher_pending / rejected。',
        compactLabel: 'publish',
      },
    ],
    routes: [
      { label: '普通 X 账号', steps: ['收集者-X', '判断者-Crypto', '搜索者', '编写者1', '编写者2', '发布者'] },
      { label: 'X AI账号', steps: ['收集者-X', '判断者-AI', '搜索者', '编写者1', '编写者2', '发布者'] },
    ],
  },
  {
    id: 'crypto_write_flow',
    title: 'Crypto 信源全文',
    badge: 'write_flow',
    summary: '外媒全文站点抓到完整文章后，先查重，再由 Crypto 判断者决定是否进入写作发布。',
    sourceEntry: "tasks.source = 'non_mainstream_media'",
    routingNote: 'CoinDesk / Cointelegraph / Decrypt 可由 Telegram-first 提前发现，成功抓到正文后仍落到同一条 Crypto 全文链路。',
    defaultStatus: "pending -> deduped / searched -> publisher_pending",
    filterTags: ['crypto'],
    nodes: [
      {
        id: 'crypto_collect',
        name: 'Crypto 收集者',
        kind: 'collector',
        description: '由 non_mainstream_media 统一发现文章、抓正文、解析作者和发布时间。',
        usesAi: false,
        output: "写入 tasks.source='non_mainstream_media'，提交 write_flow job。",
        compactLabel: 'collect',
      },
      {
        id: 'crypto_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '先与 Odaily 历史和运行中候选做精确、向量与必要 AI 复核查重。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '判重则结束；非重复内容进入判断者-Crypto。',
        compactLabel: 'search',
      },
      {
        id: 'crypto_judge',
        name: '判断者-Crypto',
        kind: 'judge',
        description: '判断外媒全文是否值得改写成 Odaily 快讯。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: "保留后 news_type='non_mainstream_media'。",
        compactLabel: 'judge_crypto',
      },
      {
        id: 'crypto_write',
        name: '编写者1',
        kind: 'writer',
        description: '使用主流外媒快讯模板，把媒体原文压缩为中文快讯。',
        usesAi: true,
        model: 'odaily-gpt-writer',
        reasoningEffort: 'low',
        output: '生成草稿标题与正文。',
        compactLabel: 'write',
      },
      {
        id: 'crypto_format',
        name: '编写者2',
        kind: 'formatter',
        description: '统一格式，保留 sourceUrl 和来源名。',
        usesAi: false,
        output: '产出最终稿并交给发布者。',
        compactLabel: 'format',
      },
      {
        id: 'crypto_publish',
        name: '发布者',
        kind: 'publisher',
        description: '根据常规发布者规则决定自动发出或挂后台。',
        usesAi: false,
        output: '自动发布或后台待审。',
        compactLabel: 'publish',
      },
    ],
  },
  {
    id: 'crypto_alert_flow',
    title: 'Crypto 标题提醒',
    badge: 'alert_only',
    summary: '只拿标题或摘要的站点不进入写作，先判断领域，再查重提醒值班编辑。',
    sourceEntry: "tasks.source = 'external_media_alert'",
    routingNote: 'The Block 当前固定停留在 alert_only；Telegram 命中后直接入标题提醒，不抓正文。',
    defaultStatus: 'pending -> notified / discarded / duplicate',
    filterTags: ['crypto', 'alert'],
    nodes: [
      {
        id: 'crypto_alert_collect',
        name: 'Crypto 收集者',
        kind: 'collector',
        description: '抓取标题、摘要和来源链接，不要求正文可用。',
        usesAi: false,
        output: "写入 tasks.source='external_media_alert'，提交 alert_only job。",
        compactLabel: 'collect',
      },
      {
        id: 'crypto_alert_domain',
        name: '领域判断',
        kind: 'judge',
        description: '判断标题是否属于需要提醒的 Crypto 主题。',
        usesAi: true,
        model: '按当前 alert 判断配置',
        output: '不相关内容丢弃；相关内容进入提醒查重。',
        compactLabel: 'domain_judge',
      },
      {
        id: 'crypto_alert_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '针对标题提醒历史和 Odaily 参考集合做去重。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '重复提醒不再推送；新提醒进入 notify。',
        compactLabel: 'search',
      },
      {
        id: 'crypto_alert_notify',
        name: '提醒者',
        kind: 'notify',
        description: '把有价值的新标题提醒送到通知渠道和信息流。',
        usesAi: false,
        output: '发送提醒，不进入编写者和发布者。',
        compactLabel: 'notify',
      },
    ],
  },
  {
    id: 'ai_write_flow',
    title: 'AI 信源全文',
    badge: 'write_flow',
    summary: 'AI/半导体信源抓到完整文章后，先查重，再由判断者-AI筛出真正重要的产业新闻。',
    sourceEntry: "tasks.source = 'ai_source'",
    routingNote: 'AI信源全文保留后写入 news_type=ai_source，但写作仍复用主流外媒快讯模板。',
    defaultStatus: 'pending -> deduped -> publisher_pending',
    filterTags: ['ai'],
    nodes: [
      {
        id: 'ai_collect',
        name: 'AI 收集者',
        kind: 'collector',
        description: '复用 non_mainstream_media 包，按 source_group=ai_source 抓取列表和正文。',
        usesAi: false,
        output: "写入 tasks.source='ai_source'，提交 write_flow job。",
        compactLabel: 'collect',
      },
      {
        id: 'ai_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '先查 Odaily 历史和运行中候选，减少同事件重复写作。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '非重复内容进入判断者-AI。',
        compactLabel: 'search',
      },
      {
        id: 'ai_judge',
        name: '判断者-AI',
        kind: 'judge',
        description: '只保留财报、产能、供应链、政策、资本运作等重要 AI/半导体新闻。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: "保留后 news_type='ai_source'；泛泛营销或低信息密度内容丢弃。",
        compactLabel: 'judge_ai',
      },
      {
        id: 'ai_write',
        name: '编写者1',
        kind: 'writer',
        description: '将 AI 信源原文压缩成中文快讯，输入块显示为待处理AI信源原文。',
        usesAi: true,
        model: 'odaily-gpt-writer',
        reasoningEffort: 'low',
        output: '生成 AI 信源快讯草稿。',
        compactLabel: 'write',
      },
      {
        id: 'ai_format',
        name: '编写者2',
        kind: 'formatter',
        description: '统一格式，保留来源链接，路线名显示为 AI信源。',
        usesAi: false,
        output: '产出最终稿并交给发布者。',
        compactLabel: 'format',
      },
      {
        id: 'ai_publish',
        name: '发布者',
        kind: 'publisher',
        description: 'AI信源发布块当前默认未启用自动放行，通常进入后台待审。',
        usesAi: false,
        output: '挂后台或按未来规则自动发布。',
        compactLabel: 'publish',
      },
    ],
  },
  {
    id: 'ai_alert_flow',
    title: 'AI 标题提醒',
    badge: 'alert_only',
    summary: '预留的 AI 标题提醒链路，结构与 Crypto 标题提醒一致，当前暂无生产站点。',
    sourceEntry: "tasks.source = 'ai_source_alert'",
    routingNote: '链路合同已保留，未来 AI 标题类站点可直接进入 domain_judge -> search -> notify。',
    defaultStatus: 'pending -> notified / discarded / duplicate',
    filterTags: ['ai', 'alert'],
    nodes: [
      {
        id: 'ai_alert_collect',
        name: 'AI 收集者',
        kind: 'collector',
        description: '抓取 AI 信源标题或摘要，不进入全文写作。',
        usesAi: false,
        output: "写入 tasks.source='ai_source_alert'，提交 alert_only job。",
        compactLabel: 'collect',
      },
      {
        id: 'ai_alert_domain',
        name: '领域判断',
        kind: 'judge',
        description: '判断标题是否属于需要提醒的 AI/半导体主题。',
        usesAi: true,
        model: '按当前 alert 判断配置',
        output: '相关内容进入查重，不相关内容丢弃。',
        compactLabel: 'domain_judge',
      },
      {
        id: 'ai_alert_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '与标题提醒历史和 Odaily 参考集合去重。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '新提醒进入 notify。',
        compactLabel: 'search',
      },
      {
        id: 'ai_alert_notify',
        name: '提醒者',
        kind: 'notify',
        description: '只提醒，不写作，不发布。',
        usesAi: false,
        output: '发送提醒。',
        compactLabel: 'notify',
      },
    ],
  },
  {
    id: 'mixed_source',
    title: '混合信源分流',
    badge: 'classifier',
    summary: '混合站点先抓正文，再在收集器内用轻量 AI 分成 crypto、ai 或 discard。',
    sourceEntry: "non_mainstream_media_sources.source_group = 'mixed_source'",
    routingNote: '分流后不新增独立 tasks.source：crypto 写入 non_mainstream_media，ai 写入 ai_source，discard 不入库。',
    defaultStatus: 'crypto / ai / discard',
    filterTags: ['mixed', 'crypto', 'ai'],
    nodes: [
      {
        id: 'mixed_collect',
        name: '混合信源收集',
        kind: 'collector',
        description: '当前首站为 Business Insider Latest，收集器先发现列表并抓取正文。',
        usesAi: false,
        output: '准备一篇待分流原文。',
        compactLabel: 'collect',
      },
      {
        id: 'mixed_split',
        name: 'AI 轻量分流',
        kind: 'split',
        description: '在入库前判断文章更适合 Crypto、AI，或应直接丢弃。',
        usesAi: true,
        model: 'odaily-gpt-fast',
        reasoningEffort: '轻量分流',
        output: "crypto -> non_mainstream_media；ai -> ai_source；discard -> mark seen。",
        compactLabel: 'split',
      },
      {
        id: 'mixed_target',
        name: '进入既有链路',
        kind: 'split',
        description: '混合信源不维护第三条发布主线，而是复用 Crypto 全文或 AI 全文链路。',
        usesAi: false,
        output: '进入 search -> judge -> write -> format_publish -> publish，或直接丢弃。',
        compactLabel: 'route',
      },
    ],
    routes: [
      { label: 'crypto', steps: ['混合信源收集', 'AI 轻量分流', 'Crypto 信源全文链路'] },
      { label: 'ai', steps: ['混合信源收集', 'AI 轻量分流', 'AI 信源全文链路'] },
      { label: 'discard', steps: ['混合信源收集', 'AI 轻量分流', '不入库，mark seen'] },
    ],
  },
  {
    id: 'competitor',
    title: '竞品快讯',
    badge: 'write_flow',
    summary: '竞品快讯先查重，再进入 Crypto 判断和统一写作发布链路。',
    sourceEntry: "tasks.source in ('blockbeats', 'panews', 'jinse')",
    routingNote: '竞品来源不向后续发布接口透出原始来源链接；判断异常时有保守兜底路由。',
    defaultStatus: 'pending -> searched -> publisher_pending',
    filterTags: ['competitor', 'crypto'],
    nodes: [
      {
        id: 'competitor_collect',
        name: '竞品收集',
        kind: 'collector',
        description: '抓取 BlockBeats、PANews、金色等竞品快讯，并做排除词过滤。',
        usesAi: false,
        output: '写入对应竞品 source，提交 write_flow job。',
        compactLabel: 'collect',
      },
      {
        id: 'competitor_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '竞品链路是 search-first，先确认是否已被 Odaily 或运行中候选覆盖。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '非重复内容进入判断者-Crypto。',
        compactLabel: 'search',
      },
      {
        id: 'competitor_judge',
        name: '判断者-Crypto',
        kind: 'judge',
        description: '判断竞品快讯是否值得跟进，并分配写作类型。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: '保留后进入编写者1。',
        compactLabel: 'judge_crypto',
      },
      {
        id: 'competitor_write',
        name: '编写者1',
        kind: 'writer',
        description: '按常规、链上或融资模板生成 Odaily 风格快讯草稿。',
        usesAi: true,
        model: 'odaily-gpt-writer',
        reasoningEffort: 'low',
        output: '生成草稿。',
        compactLabel: 'write',
      },
      {
        id: 'competitor_format',
        name: '编写者2',
        kind: 'formatter',
        description: '统一格式，竞品来源继续隐藏原始链接。',
        usesAi: false,
        output: '最终稿进入发布者。',
        compactLabel: 'format',
      },
      {
        id: 'competitor_publish',
        name: '发布者',
        kind: 'publisher',
        description: '按常规发布者规则处理。',
        usesAi: false,
        output: '自动发布或后台待审。',
        compactLabel: 'publish',
      },
    ],
  },
  {
    id: 'jin10',
    title: '金十',
    badge: 'write_flow',
    summary: '金十快讯先用专用 Prompt 做主题白名单判断，通过后走常规快讯写作。',
    sourceEntry: "tasks.source = 'jin10'",
    routingNote: '金十判断者使用控制台维护的 jin10_judge Prompt；发布渠道默认关闭，因此通常挂后台。',
    defaultStatus: 'pending -> judged -> publisher_pending',
    filterTags: ['jin10'],
    nodes: [
      {
        id: 'jin10_collect',
        name: '金十收集',
        kind: 'collector',
        description: '轮询金十网页端快讯接口，首次启用只 seed 当前列表。',
        usesAi: false,
        output: "新 item 写入 tasks.source='jin10'，提交 write_flow job。",
        compactLabel: 'collect',
      },
      {
        id: 'jin10_judge',
        name: '判断者-金十',
        kind: 'judge',
        description: '读取控制台自然语言 Prompt 作为主题白名单，只输出 publish 或 discard。',
        usesAi: true,
        model: 'odaily-deepseek-review',
        reasoningEffort: 'low',
        output: "publish 后 news_type='regular'；discard 写入 off_topic。",
        compactLabel: 'judge_jin10',
      },
      {
        id: 'jin10_search',
        name: '搜索者',
        kind: 'dedupe',
        description: '通过判断后再做 Odaily 历史与运行中候选查重。',
        usesAi: true,
        model: '规则 + 向量 + 必要时 AI 复核',
        output: '非重复内容进入写作。',
        compactLabel: 'search',
      },
      {
        id: 'jin10_write',
        name: '编写者1',
        kind: 'writer',
        description: '按 X 常规模板处理金十快讯材料，不向 Prompt 强调金十来源名。',
        usesAi: true,
        model: 'odaily-gpt-writer',
        reasoningEffort: 'low',
        output: '生成常规快讯草稿。',
        compactLabel: 'write',
      },
      {
        id: 'jin10_format',
        name: '编写者2',
        kind: 'formatter',
        description: '统一标题正文格式，金十来源不透出原始来源链接。',
        usesAi: false,
        output: '最终稿进入发布者。',
        compactLabel: 'format',
      },
      {
        id: 'jin10_publish',
        name: '发布者',
        kind: 'publisher',
        description: '通过 jin10 渠道挂后台或按配置发布。',
        usesAi: false,
        output: '默认挂后台。',
        compactLabel: 'publish',
      },
    ],
  },
];

export const workflowPrinciples = [
  {
    title: 'write_flow vs alert_only',
    body: 'write_flow 会进入判断、查重、写作、定稿和发布；alert_only 只做领域判断、查重和提醒，不进入编写者。',
  },
  {
    title: "AI账号 X 仍是 tasks.source='x'",
    body: 'AI信源标记只影响 X 内容进入 judge_ai，不改变原始 source，也不改写作者原始字段。',
  },
  {
    title: 'tasks 是档案库',
    body: '生产主链路由 local_pipeline 串联执行，Supabase/Postgres 保存输入、阶段结果、最终状态和失败原因。',
  },
  {
    title: '本地 job 唯一键',
    body: '本地流水线用 source + source_item_id 去重，避免同一来源内容重复排队。',
  },
];

export const workflowSideNotes = [
  {
    title: '巨鲸',
    body: '独立监控链路，不进入 tasks 写作发布流程；控制台只维护地址和阈值。',
  },
  {
    title: 'Chrome 插件',
    body: '信息流和快讯生成是编辑侧工具，不承接整条自动发布主链路。',
  },
  {
    title: '审核者',
    body: '发布后异步质量检查，不改变主链路节点顺序。',
  },
];
